#!/usr/bin/env python

# small wrapper to load emacs with gdba and the right filenames

from os import execlp
from sys import argv

execlp('emacs', 'emacs',
      '--eval', '(load-file (expand-file-name "~/.emacs.d/load-gdba.el"))',
      '--eval', '(load-gdba "%s")' % ' '.join(argv[1:]))
